const GeoLayout dk_Half[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, dk_Half_Switch_Half_Kong_DL_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Half_Switch_Half_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, dk_Closed_Switch_Closed_Kong_DL_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Closed_Switch_Closed_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Left_Kong[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Left_Switch_Left_Kong_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, dk_Left_Switch_Left_Kong_DL_mesh_layer_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Right[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Switch_Option_Right_Kong_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, dk_Switch_Option_Right_Kong_DL_mesh_layer_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Up_Kong[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Up_Kong_Switch_Option_Up_Kong_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, dk_Up_Kong_Switch_Option_Up_Kong_DL_mesh_layer_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Down_Kong[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Down_Kong_Switch_Option_Down_Kong_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, dk_Down_Kong_Switch_Option_Down_Kong_DL_mesh_layer_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Dead_Kong[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Dead_Kong_Switch_Option_Dead_Kong_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, dk_Dead_Kong_Switch_Option_Dead_Kong_DL_mesh_layer_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Angry_Kong[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Angry_Kong_Switch_Option_Angry_Kong_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, dk_Angry_Kong_Switch_Option_Angry_Kong_DL_mesh_layer_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 37, 0, 0, dk_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 37, 0, 0, dk_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 37, 0, 0, dk_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_ALPHA, 37, 0, 0, dk_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_ALPHA, 37, 0, 0, dk_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_ALPHA, dk_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Torso_Switch[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Switch_Option_Torso_with_Tie_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Spin[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -44, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Switch_Option_Spin_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, dk_Switch_Option_Spin_DL_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_ALPHA, dk_Switch_Option_Spin_DL_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Switch_Option_Half_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Switch_Option_Half_Switch_Half_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Switch_Option_Closed_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Switch_Option_Closed_Switch_Closed_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Switch_Option_Left_Kong_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Switch_Option_Left_Switch_Left_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Switch_Option_Right_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Switch_Option_Switch_Option_Right_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Switch_Option_Up_Kong_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Switch_Option_Up_Kong_Switch_Option_Up_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Switch_Option_Down_Kong_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Switch_Option_Down_Kong_Switch_Option_Down_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Switch_Option_Dead_Kong_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Switch_Option_Dead_Kong_Switch_Option_Dead_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Switch_Option_Angry_Kong_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Switch_Option_Angry_Kong_Switch_Option_Angry_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Switch_Option_Left_Hand_Open_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 37, 0, 0, dk_Switch_Option_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Switch_Option_Right_Hand_Open_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 37, 0, 0, dk_Switch_Option_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Switch_Option_Right_Hand_Peace_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 37, 0, 0, dk_Switch_Option_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Switch_Option_Right_Hand_Cap_006[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 37, 0, 0, dk_Switch_Option_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Switch_Option_Right_Hand_Wing_Cap_006[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 37, 0, 0, dk_Switch_Option_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, dk_Switch_Option_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Switch_Option_Torso_Switch_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Switch_Option_Switch_Option_Torso_with_Tie_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Switch_Option_Spin_001[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -44, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Switch_Option_Switch_Option_Spin_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Half_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Half_Switch_Half_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Closed_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Closed_Switch_Closed_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Left_Kong_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Left_Switch_Left_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Right_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Switch_Option_Right_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Up_Kong_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Up_Kong_Switch_Option_Up_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Down_Kong_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Down_Kong_Switch_Option_Down_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Dead_Kong_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Dead_Kong_Switch_Option_Dead_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Angry_Kong_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Angry_Kong_Switch_Option_Angry_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Left_Hand_Open_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 37, 0, 0, dk_Switch_Option_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Right_Hand_Open_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 37, 0, 0, dk_Switch_Option_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Right_Hand_Peace_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 37, 0, 0, dk_Switch_Option_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Right_Hand_Cap_006[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 37, 0, 0, dk_Switch_Option_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Right_Hand_Wing_Cap_006[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 37, 0, 0, dk_Switch_Option_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Torso_Switch_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Switch_Option_Torso_with_Tie_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Spin_001[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -44, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Switch_Option_Spin_DL_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, custom_dkroll_switch),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -44, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, dk_Switch_Option_Butt_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_move_mario_part_from_parent),
						GEO_ASM(0, geo_mario_tilt_torso),
						GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 42, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 134, 59, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_head_rotation),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_custom_dk_head_switch),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Head_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Half_001),
													GEO_BRANCH(1, dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Closed_001),
													GEO_BRANCH(1, dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Left_Kong_001),
													GEO_BRANCH(1, dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Right_001),
													GEO_BRANCH(1, dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Up_Kong_001),
													GEO_BRANCH(1, dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Down_Kong_001),
													GEO_BRANCH(1, dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Dead_Kong_001),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Angry_Kong_001),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 110, 11, 103, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, dk_Switch_Option_Left_Arm_Color_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 82, 0, 0, dk_Switch_Option_Left_Forearm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 98, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Left_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Left_Hand_Open_001),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 80, -47, 79, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Left_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 111, 11, -101, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, dk_Switch_Option_Right_Arm_Color_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 82, 0, 0, dk_Switch_Option_Right_Forearm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 98, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Right_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Right_Hand_Open_001),
												GEO_BRANCH(1, dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Right_Hand_Peace_001),
												GEO_BRANCH(1, dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Right_Hand_Cap_006),
												GEO_BRANCH(1, dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Right_Hand_Wing_Cap_006),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 80, -47, -79, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Right_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Torso_Switch_DL_mesh_layer_1),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Torso_Switch_001),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 19, -5, 40, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, dk_Switch_Option_Left_Thigh_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 37, 0, 0, dk_Switch_Option_Left_Leg_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 1, dk_Switch_Option_Left_Shoe_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 19, -5, -41, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, dk_Switch_Option_Right_Thigh_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 37, 0, 0, dk_Switch_Option_Right_Leg_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 1, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(2, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Right_Shoe_DL_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1_jump_dk_Switch_Option_Spin_001),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_Mario_001[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -44, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_SWITCH_CASE(0, custom_dkroll_switch),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -44, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dk_Switch_Option_Butt_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_move_mario_part_from_parent),
								GEO_ASM(0, geo_mario_tilt_torso),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 42, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 134, 59, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_mario_head_rotation),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_custom_dk_head_switch),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Switch_Option_Head_DL_mesh_layer_1),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, dk_Switch_Option_Half_001),
															GEO_BRANCH(1, dk_Switch_Option_Closed_001),
															GEO_BRANCH(1, dk_Switch_Option_Left_Kong_001),
															GEO_BRANCH(1, dk_Switch_Option_Right_001),
															GEO_BRANCH(1, dk_Switch_Option_Up_Kong_001),
															GEO_BRANCH(1, dk_Switch_Option_Down_Kong_001),
															GEO_BRANCH(1, dk_Switch_Option_Dead_Kong_001),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, dk_Switch_Option_Angry_Kong_001),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 110, 11, 103, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dk_Switch_Option_Left_Arm_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 82, 0, 0, dk_Switch_Option_Left_Forearm_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_SWITCH_CASE(1, geo_switch_mario_hand),
													GEO_OPEN_NODE(),
														GEO_NODE_START(),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 98, 0, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_ASM(1, geo_mario_hand_foot_scaler),
																GEO_SCALE(LAYER_FORCE, 65536),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Switch_Option_Left_Hand_DL_mesh_layer_1),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_BRANCH(1, dk_Switch_Option_Left_Hand_Open_001),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 80, -47, 79, -15, 33, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, dk_Switch_Option_Left_Wing_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 111, 11, -101, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dk_Switch_Option_Right_Arm_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 82, 0, 0, dk_Switch_Option_Right_Forearm_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_SWITCH_CASE(0, geo_switch_mario_hand),
													GEO_OPEN_NODE(),
														GEO_NODE_START(),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 98, 0, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_ASM(0, geo_mario_hand_foot_scaler),
																GEO_SCALE(LAYER_FORCE, 65536),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Switch_Option_Right_Hand_DL_mesh_layer_1),
																GEO_CLOSE_NODE(),
																GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_BRANCH(1, dk_Switch_Option_Right_Hand_Open_001),
														GEO_BRANCH(1, dk_Switch_Option_Right_Hand_Peace_001),
														GEO_BRANCH(1, dk_Switch_Option_Right_Hand_Cap_006),
														GEO_BRANCH(1, dk_Switch_Option_Right_Hand_Wing_Cap_006),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 80, -47, -79, 15, -33, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, dk_Switch_Option_Right_Wing_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Switch_Option_Torso_Switch_DL_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, dk_Switch_Option_Torso_Switch_001),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 19, -5, 40, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dk_Switch_Option_Left_Thigh_Color_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 37, 0, 0, dk_Switch_Option_Left_Leg_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 1, dk_Switch_Option_Left_Shoe_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 19, -5, -41, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dk_Switch_Option_Right_Thigh_Color_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 37, 0, 0, dk_Switch_Option_Right_Leg_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 1, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(2, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Switch_Option_Right_Shoe_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, dk_Switch_Option_Spin_001),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, dk_7_Cap_State_Switch_opt2_7_Cap_State_Switch_opt1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt1_jump_dk_Half[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Half_Switch_Half_Kong_DL_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Half_Switch_Half_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt1_jump_dk_Closed[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Closed_Switch_Closed_Kong_DL_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Closed_Switch_Closed_Kong_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt1_jump_dk_Left_Kong[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Left_Switch_Left_Kong_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Left_Switch_Left_Kong_DL_mesh_layer_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt1_jump_dk_Right[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Right_Kong_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Right_Kong_DL_mesh_layer_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt1_jump_dk_Up_Kong[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Up_Kong_Switch_Option_Up_Kong_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Up_Kong_Switch_Option_Up_Kong_DL_mesh_layer_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt1_jump_dk_Down_Kong[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Down_Kong_Switch_Option_Down_Kong_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Down_Kong_Switch_Option_Down_Kong_DL_mesh_layer_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt1_jump_dk_Dead_Kong[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Dead_Kong_Switch_Option_Dead_Kong_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Dead_Kong_Switch_Option_Dead_Kong_DL_mesh_layer_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt1_jump_dk_Angry_Kong[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Angry_Kong_Switch_Option_Angry_Kong_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Angry_Kong_Switch_Option_Angry_Kong_DL_mesh_layer_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt1_jump_dk_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 37, 0, 0, dk_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt1_jump_dk_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 37, 0, 0, dk_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt1_jump_dk_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 37, 0, 0, dk_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt1_jump_dk_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 37, 0, 0, dk_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt1_jump_dk_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 37, 0, 0, dk_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt1_jump_dk_Torso_Switch[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Torso_with_Tie_DL_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt1_jump_dk_Spin[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, -44, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Spin_DL_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Spin_DL_mesh_layer_6),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Switch_Option_Spin_DL_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_7_Cap_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, custom_dkroll_switch),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -44, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, dk_Butt_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_move_mario_part_from_parent),
						GEO_ASM(0, geo_mario_tilt_torso),
						GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 42, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 134, 59, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_head_rotation),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_custom_dk_head_switch),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Head_DL_mesh_layer_6),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Head_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, dk_7_Cap_State_Switch_opt1_jump_dk_Half),
													GEO_BRANCH(1, dk_7_Cap_State_Switch_opt1_jump_dk_Closed),
													GEO_BRANCH(1, dk_7_Cap_State_Switch_opt1_jump_dk_Left_Kong),
													GEO_BRANCH(1, dk_7_Cap_State_Switch_opt1_jump_dk_Right),
													GEO_BRANCH(1, dk_7_Cap_State_Switch_opt1_jump_dk_Up_Kong),
													GEO_BRANCH(1, dk_7_Cap_State_Switch_opt1_jump_dk_Down_Kong),
													GEO_BRANCH(1, dk_7_Cap_State_Switch_opt1_jump_dk_Dead_Kong),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, dk_7_Cap_State_Switch_opt1_jump_dk_Angry_Kong),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 110, 11, 103, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, dk_Left_Arm_Color_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 82, 0, 0, dk_Left_Forearm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 98, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Left_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, dk_7_Cap_State_Switch_opt1_jump_dk_Left_Hand_Open),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 80, -47, 79, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Left_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 111, 11, -101, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, dk_Right_Arm_Color_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_TRANSPARENT, 82, 0, 0, dk_Right_Forearm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 98, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Right_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, dk_7_Cap_State_Switch_opt1_jump_dk_Right_Hand_Open),
												GEO_BRANCH(1, dk_7_Cap_State_Switch_opt1_jump_dk_Right_Hand_Peace),
												GEO_BRANCH(1, dk_7_Cap_State_Switch_opt1_jump_dk_Right_Hand_Cap),
												GEO_BRANCH(1, dk_7_Cap_State_Switch_opt1_jump_dk_Right_Hand_Wing_Cap),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 80, -47, -79, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Right_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Torso_Switch_DL_mesh_layer_4),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Torso_Switch_DL_mesh_layer_1),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, dk_7_Cap_State_Switch_opt1_jump_dk_Torso_Switch),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 19, -5, 40, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, dk_Left_Thigh_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 37, 0, 0, dk_Left_Leg_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 1, dk_Left_Shoe_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 19, -5, -41, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, dk_Right_Thigh_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 37, 0, 0, dk_Right_Leg_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 1, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(2, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_Right_Shoe_DL_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, dk_7_Cap_State_Switch_opt1_jump_dk_Spin),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dk_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 200),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 32768),
			GEO_OPEN_NODE(),
				GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_ALPHA << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(LAYER_TRANSPARENT << 2, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, custom_dkroll_switch),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -44, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dk_Butt_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 42, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 134, 59, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_custom_dk_head_switch),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, dk_Head_DL_mesh_layer_6),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Head_DL_mesh_layer_1),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, dk_Half),
																	GEO_BRANCH(1, dk_Closed),
																	GEO_BRANCH(1, dk_Left_Kong),
																	GEO_BRANCH(1, dk_Right),
																	GEO_BRANCH(1, dk_Up_Kong),
																	GEO_BRANCH(1, dk_Down_Kong),
																	GEO_BRANCH(1, dk_Dead_Kong),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, dk_Angry_Kong),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 110, 11, 103, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dk_Left_Arm_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 82, 0, 0, dk_Left_Forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(1, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 98, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(1, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Left_Hand_DL_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, dk_Left_Hand_Open),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_FORCE, 80, -47, 79, -15, 33, -133),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_ALPHA, dk_Left_Wing_DL_mesh_layer_4),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 111, 11, -101, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dk_Right_Arm_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 82, 0, 0, dk_Right_Forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 98, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(0, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Right_Hand_DL_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, dk_Right_Hand_Open),
																GEO_BRANCH(1, dk_Right_Hand_Peace),
																GEO_BRANCH(1, dk_Right_Hand_Cap),
																GEO_BRANCH(1, dk_Right_Hand_Wing_Cap),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_FORCE, 80, -47, -79, 15, -33, -133),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_ALPHA, dk_Right_Wing_DL_mesh_layer_4),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_ALPHA, dk_Torso_Switch_DL_mesh_layer_4),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Torso_Switch_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, dk_Torso_Switch),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 19, -5, 40, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dk_Left_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 37, 0, 0, dk_Left_Leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 1, dk_Left_Shoe_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 19, -5, -41, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dk_Right_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 37, 0, 0, dk_Right_Leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 1, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_Right_Shoe_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, dk_Spin),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, dk_7_Cap_State_Switch_opt1),
					GEO_BRANCH(1, dk_Mario_001),
					GEO_BRANCH(1, dk_Mario_001),
				GEO_CLOSE_NODE(),
				GEO_ASM((LAYER_OPAQUE << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_ALPHA << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_TRANSPARENT << 2) | 1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dk_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, dk_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, dk_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, dk_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
